name: Blacklist-Eintrag
description: Spieler zur Blacklist vorschlagen
title: "Blacklist: <SpielerName>"
labels: ["blacklist"]
body:
  - type: input
    id: name
    attributes:
      label: Spielername
      placeholder: SpielerName
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Grund / Beleg
      placeholder: Kurzer Grund (Beispiel, Link, Beleg)
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Dein Ingame-Name
    validations:
      required: false
